version: '1.0.1-{branch}-{build}'
init:
  - git config --global core.autocrlf true
image: Visual Studio 2017    
branches:
  only:
    - master
    - dev
install:
  - scripts\appveyor_install.cmd
test_script:
  - scripts\appveyor_tests.cmd
build_script:
  - scripts\appveyor_build.cmd
artifacts:
- path: 'src\Steeltoe.CloudFoundry.Connector\bin\Release\*.nupkg'
- path: 'src\Steeltoe.CloudFoundry.Connector.MySql\bin\Release\*.nupkg'
- path: 'src\Steeltoe.CloudFoundry.Connector.Redis\bin\Release\*.nupkg'
- path: 'src\Steeltoe.CloudFoundry.Connector.PostgreSql\bin\Release\*.nupkg'
- path: 'src\Steeltoe.CloudFoundry.Connector.Rabbit\bin\Release\*.nupkg'
- path: 'src\Steeltoe.CloudFoundry.Connector.OAuth\bin\Release\*.nupkg'
deploy:
- provider: NuGet
  skip_symbols: true
  artifact: /.*\.nupkg/
  server: https://www.myget.org/F/steeltoemaster/api/v2/package
  api_key:
    secure: 246ApObnMYYvzDo9Ki72CxxuKfuoqYbrbUK2HLevGIGHXYY6f0OkAdE3EWCwNJ7g
  on:
    branch: master
    appveyor_repo_tag: false
- provider: NuGet
  skip_symbols: true
  artifact: /.*\.nupkg/
  server: https://www.myget.org/F/steeltoedev/api/v2/package
  api_key:
    secure: 246ApObnMYYvzDo9Ki72CxxuKfuoqYbrbUK2HLevGIGHXYY6f0OkAdE3EWCwNJ7g
  on:
    branch: dev
    appveyor_repo_tag: false
- provider: NuGet
  skip_symbols: true
  artifact: /.*\.nupkg/
  api_key:
    secure: RGkpu8xIMDC75IAd1qPRdueeTaYj+ddW2bNEw8S7e81940ELu+WV04uWAzqV34/C
  on:
    branch: master
    appveyor_repo_tag: true
